/**
 * Autonomous Status Maintenance (WS8) — the Status Synchronizer.
 *
 * When a work item's declared status or an evidence state changes, the change
 * is applied to the registry (the single source of truth) and the derived
 * artifacts (state.json lastComputed, dashboard.json, dashboard doc, minimal
 * context, next-work-item.json) are regenerated by the CLI. No human edits the
 * dashboard, closure matrix, or program state directly.
 *
 * This module owns the legal-transition rules and the registry write-back.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { REGISTRY_DIR } from "./registry.ts";
import type { WorkItemStatus, EvidenceState } from "./types.ts";

/** Declared status is a subset of the status vocabulary; READY/BLOCKED are computed. */
export type DeclaredStatus = "OPEN" | "IN_PROGRESS" | "COMPLETE";

const LEGAL_TRANSITIONS: Record<DeclaredStatus, DeclaredStatus[]> = {
  OPEN: ["IN_PROGRESS", "COMPLETE"],
  IN_PROGRESS: ["COMPLETE", "OPEN"],
  COMPLETE: ["IN_PROGRESS"], // reopening is allowed (migration-only correction), forward again after
};

const EVIDENCE_ORDER: EvidenceState[] = ["PENDING", "SUBMITTED", "VERIFIED", "CERTIFIED"];

export function isDeclared(status: WorkItemStatus): status is DeclaredStatus {
  return status === "OPEN" || status === "IN_PROGRESS" || status === "COMPLETE";
}

export function assertLegalTransition(from: DeclaredStatus, to: DeclaredStatus): void {
  if (from === to) return;
  if (!LEGAL_TRANSITIONS[from].includes(to)) {
    throw new Error(`Illegal status transition ${from} -> ${to}. Legal: ${LEGAL_TRANSITIONS[from].join(", ")}.`);
  }
}

export function assertLegalEvidenceTransition(from: EvidenceState, to: EvidenceState): void {
  const fi = EVIDENCE_ORDER.indexOf(from);
  const ti = EVIDENCE_ORDER.indexOf(to);
  if (ti < fi) {
    throw new Error(`Evidence cannot regress ${from} -> ${to} (append-only / migration-only).`);
  }
}

function readRaw<T>(file: string): T {
  return JSON.parse(readFileSync(join(REGISTRY_DIR, file), "utf8")) as T;
}

function writeRaw(file: string, data: unknown): void {
  writeFileSync(join(REGISTRY_DIR, file), JSON.stringify(data, null, 2) + "\n", "utf8");
}

/** Persist a work-item declared-status change, enforcing legal transitions. */
export function setWorkItemStatus(id: string, to: DeclaredStatus): { from: DeclaredStatus; to: DeclaredStatus } {
  const doc = readRaw<{ workItems: { id: string; declaredStatus: WorkItemStatus }[] }>("work-items.json");
  const wi = doc.workItems.find((w) => w.id === id);
  if (!wi) throw new Error(`Unknown work item: ${id}`);
  if (!isDeclared(wi.declaredStatus)) throw new Error(`${id} has a non-declared status ${wi.declaredStatus}`);
  const from = wi.declaredStatus;
  assertLegalTransition(from, to);
  wi.declaredStatus = to;
  writeRaw("work-items.json", doc);
  return { from, to };
}

/** Persist an evidence-state advance, enforcing monotonic (non-regressing) transitions. */
export function setEvidenceState(evidenceId: string, to: EvidenceState): { from: EvidenceState; to: EvidenceState } {
  const doc = readRaw<{ evidence: { id: string; state: EvidenceState }[] }>("evidence-registry.json");
  const ev = doc.evidence.find((e) => e.id === evidenceId);
  if (!ev) throw new Error(`Unknown evidence id: ${evidenceId}`);
  const from = ev.state;
  assertLegalEvidenceTransition(from, to);
  ev.state = to;
  writeRaw("evidence-registry.json", doc);
  return { from, to };
}

/** Stamp state.json lastComputed so the registry records when it was last compiled. */
export function stampLastComputed(iso: string): void {
  const state = readRaw<Record<string, unknown>>("state.json");
  state.lastComputed = iso;
  writeRaw("state.json", state);
}
